### ISSUE TITLE
Error reinitializing filters!

### ISSUE THREAD

**Issue by bowieinflux** [viler-int10h/FFmpeg-CRT-transform#2]
Getting this error on windows. I downloaded the repo, got the FFMpeg binaries from https://www.gyan.dev/ffmpeg/builds/ and put them in the project folder. When i run

```
PS C:\Users\myusername\Desktop\FFmpeg-CRT-transform> .\ffcrt .\presets\color-fuzzyx1.cfg .\IMG_4172.mp4 output.mp4

Input frame count: 73
---------------------------
Bezel:
[Parsed_lenscorrection_13 @ 0000026627703600] Failed to configure output pad on Parsed_lenscorrection_13
Error reinitializing filters!
Failed to inject frame into filter network: Cannot allocate memory
Error while processing the decoded data for stream #0:0****
```

**Comment by viler-int10h** [comment]
@bowieinflux: What is the source resolution of your input video?  "Cannot allocate memory" may happen if the dimensions _after_ input pre-scaling get too large.  That particular preset .cfg assumes an input somewhere around 320x200 or so - if it's bigger than that, try decreasing the PRESCALE_BY factor.

FFmpeg generally consumes RAM linearly with the dimensions of the processed frames.. so the limit of course depends on your system total, too.

(BTW, this is probably unrelated, but PS is not needed fro this.)

**Comment by bowieinflux** [comment]
@viler-int10h That was it - tried a video around your suggested res and it worked great. Thank you and killer project!

**Comment by viler-int10h** [comment]
Excellent!
